In [21]:
import numpy as np

### Selecting values

In [22]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [24]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [25]:
arr[8:] = 100
arr

array([  0,   1,   2,   3,   4,   5,   6,   7, 100, 100, 100])

### Copying and slicing 

In [26]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
slic = arr[:6].copy()
slic

array([0, 1, 2, 3, 4, 5])

In [28]:
slic[:] = 10
slic

array([10, 10, 10, 10, 10, 10])

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
slic_slic = slic[:3]
slic_slic

array([10, 10, 10])

In [31]:
slic_slic[:] = 100
slic_slic

array([100, 100, 100])

In [32]:
slic

array([100, 100, 100,  10,  10,  10])

### Selecting values matrix

In [34]:
arr_mat = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [41]:
arr_mat[1][1]

25

In [42]:
arr_mat[2,1]

40

In [43]:
arr_mat[:2,1:]

array([[10, 15],
       [25, 30]])

In [55]:
arr_mat[1:,:2]

array([[20, 25],
       [35, 40]])

In [64]:
arr_mat = np.arange(50).reshape(5,10)
arr_mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [65]:
arr_mat[1:3,3:5]

array([[13, 14],
       [23, 24]])

### Conditional selection

In [56]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [59]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [60]:
arr[arr<3]

array([1, 2])