In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Zeros and ones

In [16]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Linspace and eye

In [15]:
np.linspace(0.01,99.9,100)

array([1.00000000e-02, 1.01898990e+00, 2.02797980e+00, 3.03696970e+00,
       4.04595960e+00, 5.05494949e+00, 6.06393939e+00, 7.07292929e+00,
       8.08191919e+00, 9.09090909e+00, 1.00998990e+01, 1.11088889e+01,
       1.21178788e+01, 1.31268687e+01, 1.41358586e+01, 1.51448485e+01,
       1.61538384e+01, 1.71628283e+01, 1.81718182e+01, 1.91808081e+01,
       2.01897980e+01, 2.11987879e+01, 2.22077778e+01, 2.32167677e+01,
       2.42257576e+01, 2.52347475e+01, 2.62437374e+01, 2.72527273e+01,
       2.82617172e+01, 2.92707071e+01, 3.02796970e+01, 3.12886869e+01,
       3.22976768e+01, 3.33066667e+01, 3.43156566e+01, 3.53246465e+01,
       3.63336364e+01, 3.73426263e+01, 3.83516162e+01, 3.93606061e+01,
       4.03695960e+01, 4.13785859e+01, 4.23875758e+01, 4.33965657e+01,
       4.44055556e+01, 4.54145455e+01, 4.64235354e+01, 4.74325253e+01,
       4.84415152e+01, 4.94505051e+01, 5.04594949e+01, 5.14684848e+01,
       5.24774747e+01, 5.34864646e+01, 5.44954545e+01, 5.55044444e+01,
      

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Rand, Randn and Randint

In [18]:
np.random.rand(5,5)

array([[0.96301871, 0.74056356, 0.13624056, 0.86185462, 0.8512508 ],
       [0.24390028, 0.59674445, 0.14712926, 0.51412479, 0.67717374],
       [0.88339508, 0.10155994, 0.58877668, 0.35915864, 0.70134138],
       [0.7471004 , 0.2581766 , 0.0845798 , 0.75086819, 0.58619206],
       [0.38866975, 0.49665552, 0.06755896, 0.51549784, 0.13416646]])

In [21]:
np.random.randn(4,4)

array([[-1.50255517,  0.90972725, -0.44135127, -0.60899814],
       [ 0.05102794, -0.4172716 ,  0.42963455,  0.42858198],
       [-0.58960492, -0.58486783,  2.03120277,  1.63121031],
       [ 1.67472572, -0.37522599, -0.37556288,  0.43249388]])

In [23]:
np.random.randint(-20,20,100)

array([  9, -12,  -3, -10,  18,  10, -10, -20, -20,   3,  18,   7,   8,
         4,   0,   4,  11,  -2,  11, -15,  -8,  -2, -16,  14,   0,  10,
       -10,  -5, -11,   2,  18,   5,  -4,  13,  -8,  -6,   4,  -9,  12,
         1, -18,  -9,  17,  17, -11,   2, -13, -10, -15,  11,   7,  14,
        11,  -7,  -7,  15,   6,  -1,  -4,  -1, -12, -18, -16,  12,  -9,
        -7, -19,  -4,  -7, -11, -12,  14,  14,  -5,   8,  -9,  -9, -16,
        -6, -14,  -2, -17,   3,  -9,  -1,  -9,   5,   7, -17,   0,  -4,
        16,  14,  -7,  13,   8,  -6,  12,  -3,  -3])

In [54]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### Reshape, max, min and their position

In [56]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
ranarr

array([ 3, 14, 12, 41, 29,  0, 19, 33, 30, 35])

In [58]:
ranarr.max()

41

In [59]:
ranarr.min()

0

In [60]:
ranarr.argmax()

3

In [61]:
ranarr.argmin()

5

In [62]:
arr.shape

(5, 5)

In [64]:
arr = arr.reshape(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
arr.shape

(25,)